### ISSUE TITLE
updated version of Rcpp Gallery post (with math and figure)

### ISSUE THREAD

**Issue by jlegewie** [RcppCore/rcpp-gallery#63]
Dirk recently send around an email encouraging previous authors to update their posts using the new features. The original version of my post actually included formulas and figures so I was happy to hear that they are now supported. The updated gist is [here](https://gist.github.com/jlegewie/6485612) and the original link in the Gallery is [here](http://gallery.rcpp.org/articles/dmvnorm-deriv-arma/).

**Comment by eddelbuettel** [comment]
Nice :)   Will take a look this evening.

**Comment by eddelbuettel** [comment]
Now posted.  

It was missing `mathjax: true` in the header, and I believe math segments need `$$` instead of just one -- can you confirm, @olmjo ?

Otherwise, looks _great_ with the equation and two charts!  Thanks for the update. (And maybe look it over at [the same URL](http://gallery.rcpp.org/articles/dmvnorm-deriv-arma/) as I did some small edits.

**Comment by olmjo** [comment]
That's right. All math has two dollar signs. Display vs. Inline is
determined by surrounding whitespace. The documentation is at <
https://github.com/jjallaire/rcpp-gallery/wiki/Contributing-to-the-Rcpp-Gallery

> .

Jonathan Olmsted

**Comment by jlegewie** [comment]
Thanks, looks good!
